parameters = c("RMA.invariantset.medianpolish" ,
               "RMA.constant.medianpolish" ,
               "RMA.robust",
               "RMA.invariantset.mas" ,
               "RMA.constant.mas" ,
               "RMA.quantile.mas" ,
               "RMA.invariantset.liwong" ,
               "RMA.constant.liwong" ,
               "RMA.quantile.liwong" ,
               "MAS.quantiles" ,
               "MAS5" ,
               "MAS.invariantset",
               "MAS2.quantile.medianpolish" ,
               "MAS.medianpolish" ,
               "MAS2.invariantset.medianpolish" ,
               "MAS2.quantile.liwong" ,
               "MAS.liwong" ,
               "MAS2.invariantset.liwong" ,
               "MASpm.quantile.mas" ,
               "MASpm.constant.mas" ,
               "MASpm.invariantset.mas" ,
               "MASpm.quantile.medianpolish" ,
               "MASpm.constant.medianpolish" ,
               "MASpm.invariantset.medianpolish" ,
               "MASpm.quantile.liwong" ,
               "MASpm.constant.liwong" ,
               "MASpm.invariantset.liwong",
               "rma",
               "gcrma",
               "mas5",
               "liwong")
